### ISSUE TITLE
Confirm that the shell code installation gives me something I an execute from in pycharm

### ISSUE THREAD

**Issue by bnlawrence** [ES-DOC/esdoc-nb-shell#2]
The shell install adds various things from various modules into the python path. How can I cleanly replicate that in my development environment?

**Comment by bnlawrence** [comment]
It looks like the best way would be to pull out the path manipulation into a script that could be added into the pycharm setup. We need these three added to the python path. However, wouldn't it be cleaner to add these as modules, rather than add them into the path?

```
 export PYTHONPATH=$PYTHONPATH:$DIR_LOCAL_REPOS/esdoc-mp/src
 export PYTHONPATH=$PYTHONPATH:$DIR_LOCAL_REPOS/esdoc-nb
 export PYTHONPATH=$PYTHONPATH:$DIR_LOCAL_REPOS/esdoc-py-client/src
```

**Comment by momipsl** [comment]
Much better to run form source when in development phase.  You should migrate you development environment accordingly by installing the shell and setting up a new pycharm project pointing to the source code folders found in the **local** subfolder.

**Comment by bnlawrence** [comment]
But you run from source when you use python setup.py development !!!

**Comment by bnlawrence** [comment]
Even if I run from source following your prescription, my problem is that in pycharm I have to add the various exports ...

**Comment by momipsl** [comment]
The point being is that you will be modifying the code base, i.e. editing the cim2 / cmip6 schemas and constraints.  By having the Git-ified source code locally you can make changes and subsequently commit them.  You can generate the CIM v2 types and have then commited to pyesdoc.  So as I said whilst we are in a development phase then there is no point going through the pypi mechanism as you suggest.
