### ISSUE TITLE
Where does the pip install in the installer put things?

### ISSUE THREAD

**Issue by bnlawrence** [ES-DOC/esdoc-nb-shell#3]
This is related to the which python issue. If I've got macports python on a mac, how do I make sure it's pip installing into that? I see a list of reuqirements, are they in my installation?

**Comment by momipsl** [comment]
Go to the command line and type 'which python'.  This is the default python and the requirements will be pipped into that.  If your default python is not the one in macports then you can update the path to your system python in your .bash_profile.  For example I use Brew on MacOSX and ensure that the brewed python is the default by adding this to my .bash_profile file:
<pre><code>export PATH=/usr/local/Cellar/python/2.7.10_2/bin:$PATH</pre></code>

Previously the installer built a local python executable and a local virtual environment in an attempt ot make it completely sealed from the local system but pygtk cannot be pip installed and it cannot be compiled against a virtual environment, hence the ystem python has to be used.

**Comment by bnlawrence** [comment]
What if you don't want to use a default python?

The statements above are not entirely correct, or at least, they're correct, but founded on an unnecessary assumption (that *everything* has to be in the installable package).  There is a middle ground, and it's the middle ground which I think is easiest for non-experts. 

If you get pygtk and graphviz into your system python (or default python or whatever python you want to use), then we should be able to use any kind of virtual install to add the esdoc tools. In general a pretty good default rule is for any kind of gui toolkit you don't want to be installing your own, you want to use a packaged version. Obviously that's not the case for one's own code.

**Comment by momipsl** [comment]
You are confused and confusing.  All you need to do is ensure that the python executable that you wish to use is available, by either aliasing or by updating your python path, prior to running an esdoc-notebook-* command.  Alternatively we could ask the user to create an environment variable called ESDOC_PYTHON which would then be used in the scripts.  Actually this latter idea seems the best.
