### ISSUE TITLE
Install/Replace/Git

### ISSUE THREAD

**Issue by bnlawrence** [ES-DOC/esdoc-nb-shell#4]
A couple of issues for the shell.

(Not for solving now, but we might want to revisit when we think about deployment.)

1) The install makes the assumption that https is the best method of getting to github/bitbucket. That's not the case for those of us behind proxy firewalls, where, if it's open, git/ssh is best.  Of course, for others, https is the right answer. It probably needs to be configurable ... 

2) The workflow for install/replace/update is not clear. Once it is installed, should one only update via git pull/push ... if so, where exactly does one do this (maybe this too will be easier/obvious once there is only one repo in place ... but even that is pulling multiple repos ... so ...)

**Comment by momipsl** [comment]
Regarding point 1. this is a simple patch.  It will be up to the user to (optionally) specify an environment variable **ESDOC_NOTEBOOK_GIT_PROTOCOL = https | ssh**.  If the user has not set this environment variable then it will default to https.  

Regarding point 2. esdoc-notebook-update performs git pulls over the shell itself and the esdoc-mp, esdoc-nb, & esdoc-py-client repos.  It also updates python dependencies (where necessary).  Therefore when you make changes to pyesdoc for example, by executing esdoc-notebook-generate, then you need to manually push these changes.  At which point another user will need to perform an esdoc-notebook-update to sync.

**Comment by momipsl** [comment]
I have committed the changes and updated the readme.  The user can now specify that they interact with git via ssh by setting the ESDOC_NOTEBOOK_GIT_PROTOCOL environment variable.
